version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - lumen-net
    depends_on:
      - redis
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: lumen-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - lumen-net

  redis:
    image: redis:7
    container_name: lumen-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - lumen-net

networks:
  lumen-net:
    driver: bridge
