version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    networks:
      - lumen-net
    depends_on:
      - redis
      - postgres
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=lumen
      - DB_USERNAME=lumen
      - DB_PASSWORD=lumen
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: lumen-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - lumen-net

  redis:
    image: redis:7
    container_name: lumen-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - lumen-net

  postgres:
    image: postgres:16-alpine
    container_name: lumen-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=lumen
      - POSTGRES_USER=lumen
      - POSTGRES_PASSWORD=lumen
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lumen-net

networks:
  lumen-net:
    driver: bridge

volumes:
  postgres_data:
